version: '3.9'

services:
  webserver:
    container_name: webserver
    restart: unless-stopped
    env_file: .env
    # ports:
    #  - "80:80"
    #  - "443:443"
    build:
      context: ./webserver/
      dockerfile: Dockerfile
      args:
        - CERTBOT_CERT_FOLDER=${CERTBOT_CERT_FOLDER}
    volumes:
      - ./webserver/templates:/etc/nginx/templates
      - certbot-env:/etc/letsencrypt/
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
      - client-app-dist:/usr/src/your-priorities/client/build/bundle
      - admin-app-dist:/usr/src/your-priorities/admin_app/dist
      - analytics-app-dist:/usr/src/your-priorities/analytics_app/dist
    network_mode: host

  your-priorities-app:
    container_name: your-priorities-app
    build: ./your-priorities-app/
    env_file: .env
    restart: unless-stopped
    build:
      context: ../../.
      dockerfile: deployment/docker/your-priorities-app/Dockerfile
    volumes:
      - client-app-dist:/usr/src/your-priorities/client/build/bundle
      - admin-app-dist:/usr/src/your-priorities/admin_app/dist
      - analytics-app-dist:/usr/src/your-priorities/analytics_app/dist
    environment:
      - NODE_ENV=production
    command: node --optimize_for_size --max_old_space_size=460 server_api/api_app.js
    network_mode: host

  your-priorities-worker:
    container_name: your-priorities-worker
    build: ./your-priorities-worker/
    env_file: .env
    build:
      context: ../../.
      dockerfile: deployment/docker/your-priorities-worker/Dockerfile
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    command: node --optimize_for_size --max_old_space_size=960 server_api/active-citizen/workers/main.js
    network_mode: host

  minio:
    image: minio/minio
    env_file: .env
    volumes:
      - data1-1:/minio_data1
      - data1-2:/minio_data2
    expose:
      - "9000"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server http://localhost/data{1...2}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  certbot:
    image: certbot/certbot
    container_name: certbot
    env_file: .env
    volumes:
      - certbot-env:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    depends_on:
      - webserver

  #ac-analytics-api:
  #  container_name: ac-anaylitcs-api
  #  build: ./ac-anaylitcs-api/
  #  env_file: .yrpri-env
  #  environment:
  #    - NODE_ENV=production
  #  networks:
  #    - app-network
volumes:
  certbot-var:
  client-app-dist:
  admin-app-dist:
  analytics-app-dist:
  web-root:
  data1-1:
  data1-2:
  certbot-env:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /root/your-priorities-app/deployment/docker/webserver/letsEncryptCerts

